CREATE TABLE cs_agents
(
    id         INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cs_name    VARCHAR(100) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_cs_agents PRIMARY KEY (id)
);

CREATE TABLE customers
(
    id            INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    customer_name VARCHAR(100) NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_customers PRIMARY KEY (id)
);

CREATE TABLE call_monitorings
(
    id              BIGINT        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    call_id         VARCHAR(50)   NOT NULL UNIQUE,
    call_timestamp  TIMESTAMP     NOT NULL,
    cs_agent_id     INT           NOT NULL,
    customer_id     INT           NOT NULL,
    sentiment_score NUMERIC(5, 2) NOT NULL,
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_call_monitorings PRIMARY KEY (id),
    CONSTRAINT fk_call_monitorings_cs_agent FOREIGN KEY (cs_agent_id) REFERENCES cs_agents (id),
    CONSTRAINT fk_call_monitorings_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
    CONSTRAINT chk_sentiment_score CHECK (sentiment_score >= 0.00 AND sentiment_score <= 100.00)
);

CREATE INDEX idx_call_monitorings_call_timestamp ON call_monitorings (call_timestamp);
CREATE INDEX idx_call_monitorings_sentiment_score ON call_monitorings (sentiment_score);
CREATE INDEX idx_call_monitorings_cs_agent_id ON call_monitorings (cs_agent_id);
CREATE INDEX idx_call_monitorings_customer_id ON call_monitorings (customer_id);
